### ISSUE TITLE
The first few messages are missed in the automatically captured control ports log. 

### ISSUE THREAD

**Issue by chenlei-CTTL** [InCNTRE/oftest#102]
OFtest provide a parameter --publish to control the automatically capture. The automatically capture files are separate by testcase and test ports. The separately test logs are convenient for crosscheck.

But I found a problem about oftest 1.0 automatically capture. The first few messages are missed in the automatically captured control ports log. Mr. Nikhill from InCNTRE suggest that parameter publish should be used with parameter -H -p -P and -T. But I used all these parameters in one command line, this problem still exits.

**Comment by jonstout** [comment]
This is a known issue. The decorator `@wireshark` was used to enable traffic captures where ever it is used. Unfortunately this does not work for every test case, and causes the initial handshake to be lost. The current work around is to use wireshark manually.

**Comment by chenlei-CTTL** [comment]
Thank you.




陈雷 CHEN Lei
主任工程师 Chief Engineer
泰尔系统实验室有线网络部 Department of Wireline Network Communication of CTTL-systems
地址/Address：北京市海淀区花园北路52号 No.52 Huayuanbei Road, Haidian District, Beijing, P.R. China
电话/Phone：+86 10 62305047
手机/Mobile：+86 18610527164
传真/Fax：+86 10 62304104
邮箱/Email：chenlei@catr.cn
网址/Web：http://www.catr.cn； http://www.chinattl.com

2015-02-05

From: Jonathan Stout
Date: 2015-02-04 23:25
To: InCNTRE/oftest
CC: chenlei-CTTL
Subject: Re: [oftest] The first few messages are missed in the automatically captured control ports log. (#102)
Closed #102 via #104.
